Create Product and User Controller
Toasted201/OpenClassroom_P07 pull request #16
Opened 2021-03-17 10:05 UTC by Toasted201

2021-03-17 10:26 UTC, TBoileau requested changes

2021-03-17 10:26 UTC, TBoileau commented on src/Controller/ProductController.php
> +    public function showProduct(Product $product, SerializerInterface $serializer)
Typer le retour de la méthode

2021-03-17 10:26 UTC, TBoileau commented on src/Controller/ProductController.php
> +        $page=$request->query->get('page', 1);
à la place de `get`, faire un `getInt`

2021-03-17 10:26 UTC, TBoileau commented on src/Controller/ProductController.php
> +        return new JsonResponse($serializer->serialize($paginated, 'json'),200,[],true);
Oubli pas les espaces après les virgules. Ne pas hésitez à installer PHP Code Sniffer et de lancer phpcbf pour nettoyer le code automatiquement

2021-03-17 10:26 UTC, TBoileau commented on src/Controller/UserController.php
> +        if ($userForm->isValid()){
Au lieu d'utiliser le composant Form, utiliser directement le Validator, et si erreurs, alors renvoyer la liste : 
```php
if (($violations = $validator->validate($user))->count() > 0) {
```

2021-03-17 10:26 UTC, TBoileau commented on src/Entity/User.php
> + *      )
Ajouter la relation pour le delete

2021-03-17 10:26 UTC, TBoileau commented on src/Form/UserFormType.php
> +}
A supprimer

2021-03-17 10:26 UTC, TBoileau commented on src/Repository/ClientRepository.php
> +    */
Supprimer le code mort

2021-03-17 10:26 UTC, TBoileau commented on src/Repository/ProductRepository.php
> +    */
Supprimer le code mort

2021-03-17 10:26 UTC, TBoileau commented on src/Repository/UserRepository.php
> +    */
Supprimer le code mort

2021-03-24 10:19 UTC, TBoileau requested changes

2021-03-24 10:19 UTC, TBoileau commented on phpcs.xml.dist
> +    <file>public/</file>
tu peux enlever ces 3 dossiers

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/AuthController.php
> + }
inutile

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +
inutile car le ParamConverter renverra une erreur dans le cas ou il ne trouve pas l'user en bdd

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +        }
Pour tous les Item Operation (GET/PUT/DELETE => /users/{id}), utiliser un Voter

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +        $user->setClient($clientRepository->find($client));
`$user->setClient($this->getUser());`

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +            return new JsonResponse($serializer->serialize($message, 'json'), 422, [], true);
Test de serializer dirtectement `$violations`

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +        if (count($violations) == 0) {
Ce `if` est inutile

2021-03-24 10:19 UTC, TBoileau commented on src/Controller/UserController.php
> +        if ($client = $user->getClient()) {
Même remarque que le GET user

2021-03-24 10:19 UTC, TBoileau commented on src/Entity/Client.php
> +    private $token;
inutile

2021-03-24 10:19 UTC, TBoileau commented on config/packages/security.yaml
> +                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
Il va te manquer une information : 
````yaml
json_login:
                check_path: /authentication_token
                username_path: title
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

2021-03-24 10:19 UTC, TBoileau commented on src/Entity/Client.php
> +    private $roles = [];
Inutile

2021-03-24 10:19 UTC, TBoileau commented on src/Entity/Client.php
> +    }
Inutile

2021-03-24 10:19 UTC, TBoileau commented on src/Entity/Client.php
> +        return array_unique($roles);
ne renvoyer que `["ROLE_USER"]`

2021-03-24 10:19 UTC, TBoileau commented on src/Entity/Client.php
> +    }
Inutile

2021-03-24 18:52 UTC, closed without merging

2021-04-02 10:45 UTC, Toasted201 commented on src/Controller/ProductController.php
> +    public function showProduct(Product $product, SerializerInterface $serializer)
ajout : JsonResponse
(fait sur toutes les méthodes)

2021-04-02 10:47 UTC, Toasted201 commented on src/Controller/ProductController.php
> +        return new JsonResponse($serializer->serialize($paginated, 'json'),200,[],true);
Installation de l'extension PHP Sniffer pour alertes visibles dans VisualCode

2021-04-02 10:50 UTC, Toasted201 commented on src/Controller/UserController.php
> +        if ($userForm->isValid()){
Suppression du formulaire et modification controller