Documentation + Voter
Toasted201/OpenClassroom_P07 pull request #18
Opened 2021-03-31 08:57 UTC by Toasted201

2021-03-31 09:21 UTC, TBoileau requested changes

2021-03-31 09:21 UTC, TBoileau commented on src/Controller/ProductController.php
> +     *                  ref=@Model(type=Product::class)),
Je pense qu'il manque quelques petites informations, car la forme n'est pas même que les données rendues

2021-03-31 09:21 UTC, TBoileau commented on src/Controller/UserController.php
> +    }
Changer de nom pour ne pas surcharger une méthode qui est bonne

2021-03-31 09:21 UTC, TBoileau commented on src/Controller/UserController.php
> +     *                  ref=@Model(type=User::class)),
Même remarque que `ProductController::listProducts`

2021-03-31 09:21 UTC, TBoileau commented on src/Controller/UserController.php
> +     *          @OA\JsonContent(ref=@Model(type=User::class)))
Attention pour la création, dans la doc, on demandera sans doute l'id (à vérifier), ce qui n'est pas nécessaire, il faut donc l'exclure de la doc, peut être en jouant avec des groups de sérialisation

2021-03-31 09:21 UTC, TBoileau commented on src/Entity/Client.php
> +    private $users;
Pas besoin de bi-directionnalité car on ne va jamais traité les users depuis client

2021-03-31 15:48 UTC, Toasted201 commented on src/Controller/UserController.php
> +     *                  ref=@Model(type=User::class)),
Ajout      
type="array",
@OA\Items()

2021-03-31 16:19 UTC, Toasted201 commented on src/Controller/UserController.php
> +     *          @OA\JsonContent(ref=@Model(type=User::class)))
ajout 
groups={"add_user"}

2021-04-01 14:42 UTC, Toasted201 commented on src/Entity/Client.php
> +    private $users;
Supprimé

2021-04-01 14:56 UTC, Toasted201 commented on src/Controller/UserController.php
> +    }
modifié en  notFoundUnlessGranted()

2021-04-01 14:57 UTC, closed without merging